### ISSUE TITLE
论文发布了吗

### ISSUE THREAD

**Issue by Noen61** [ZJU-DAILY/PromptEM#1]
论文发布了吗

**Comment by Peng-fei-Wang** [comment]
Thank you for your interest in our work. The paper is under revision, and we will prepare an online version after the revision is completed. You can watch our repository to be notified as soon as the paper becomes available.

感谢关注！ 论文正在修改中，修改完成后我们将准备在线版本。 您可以观看我们的存储库，以便在论文可用时立即收到通知。

**Comment by Peng-fei-Wang** [comment]
We have released our online version, please see [PromptEM](https://arxiv.org/pdf/2207.04802.pdf).

**Comment by Noen61** [comment]
想请教下在有监督情况下对于entity linking或者matching这种任务，使用prompt-tuning相比fine-tuning会有提升吗

**Comment by Peng-fei-Wang** [comment]
We have provided corresponding results in Appendix A. In our experiments, we find that prompt-tuning can outperform fine-tuning by designing a suitable prompt.

我们的附录中有全量有监督情况下的结果（Appendix A），在我们的实验中，通过设计合适的prompt，prompt-tuning表现能比fine-tuning更好。
