### ISSUE TITLE
classes in dataset and verbalizer are different

### ISSUE THREAD

**Issue by lihuiliullh** [ZJU-DAILY/PromptEM#3]
I notice that in the dataset, 0 means unmatched and 1 means matched.
But in verbalizer, 0 means matched and 1 means unmatched. Do you notice this difference? 

In prompt.py
classes = [
        "yes",
        "no",
    ]

**Comment by lihuiliullh** [comment]
@Peng-fei-Wang @Zeng1998

**Comment by Zeng1998** [comment]
Hello, @lihuiliullh. We are dealing with it and will notify you know when we have the results.
